# render.yaml
services:
  - type: web
    name: event-management
    env: php
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
      php artisan config:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_KEY
        generateValue: true
      # Database vars can go here or in the Render UI:
      #- key: DB_CONNECTION
      #  value: pgsql
      #- key: DB_HOST
      #  value: your-db-host
      #- key: DB_PORT
      #  value: '5432'
      #- key: DB_DATABASE
      #  value: your-db-name
      #- key: DB_USERNAME
      #  value: your-db-user
      #- key: DB_PASSWORD
      #  value: your-db-pass
